name: Build Verification

on: workflow_dispatch

jobs:
  build-verification:
    
    runs-on: ubuntu-20.04

    env:
      REPO_DIR: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
      # Checkout our Github repo
      - name: Checkout Github Repo
        uses: actions/checkout@v3
        with:
          path: go/src/github.com/${{ github.repository }}

      # Prepare the environment
      - name: Set up golang 1.19
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
          check-latest: true

      # Configure version variables for later steps, stored in our workflow env. variables
      - name: Config Version Variables
        id: config-version
        run: |
          cd ${REPO_DIR}
          echo "VERSION=$(sed -n 's/export VERSION ?= //p' Makefile | cut -d '$' -f 1)" >> $GITHUB_OUTPUT

      # Compile FDO-Support and Build Docker Images
      - name: Compile and Build Docker Images
        run: |
          cd ${REPO_DIR}
          make clean
          make
          docker image ls
        env:
          VERSION: '${{ steps.config-version.outputs.VERSION }}-${{ github.run_number }}'